const int COMPOSITION_MIN_TIME = 120;
const int COMPOSITION_MAX_TIME = 600;
const int COMPOSITION_TWO_MINUTES_LEFT = COMPOSITION_MAX_TIME - 120;
const int COMPOSITION_ONE_MINUTE_LEFT = COMPOSITION_MAX_TIME - 60;
